---
micronaut:
  application:
    name: api

---
datasources.default: {}
---
hibernate:
  hbm2ddl:
    auto: create



#hibernate:
  #cache:
    #queries: false
    #use_second_level_cache: true
    #use_query_cache: false
    #region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
