---
micronaut:
  application:
    name: api

---
datasources:
  pooled: true
  dbCreate: update
  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password: ''
  dialect: org.hibernate.dialect.H2Dialect

hibernate:
  hbm2ddl:
    auto: update
